# Generated by Django 4.2 on 2023-05-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
    ]
